version: 1

projects:
  - network: polkadot
    owner: blockops-sh
    name: blockops-sre
    branch: main
    paths:
      - k8s/argocd-deployments/manifests/fullnodes/polkadot-archive.yml

  - network: polkadot
    owner: blockops-sh
    name: blockops-sre
    branch: main
    paths:
      - k8s/argocd-deployments/manifests/fullnodes/polkadot-kusama-rpc.yml


  

  
