apiVersion: apps/v1
kind: Deployment
metadata:
  name: ponos
  namespace: ponos
  annotations:
    prometheus.io/port: '8700'
    prometheus.io/scrape: 'true'
  labels:
    app: ponos
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: ponos
  template:
    metadata:
      labels:
        app: ponos
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Equal
          key: blockops
          value: testnet
      containers:
      - name: ponos
        image: ##IMAGE_URL##
        volumeMounts:
          - name: github-pem
            mountPath: /app/gh.pem
            subPath: gh.pem
        ports:
          - containerPort: 8700
        env:
          - name: GITHUB_APP_ID
            valueFrom:
              configMapKeyRef:
                name: ponos-config
                key: GITHUB_APP_ID
          - name: GITHUB_INSTALL_ID
            valueFrom:
              configMapKeyRef:
                name: ponos-config
                key: GITHUB_INSTALL_ID
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: ponos-config
                key: PORT
          - name: GITHUB_PEM_KEY
            valueFrom:
              configMapKeyRef:
                name: ponos-config
                key: GITHUB_PEM_KEY
          - name: SLACK_SIGNING_SECRET
            valueFrom:
              secretKeyRef:
                name: ponos-secret
                key: SLACK_SIGNING_SECRET
          - name: MYSQL_DSN
            valueFrom:
              secretKeyRef:
                name: ponos-secret
                key: MYSQL_DSN
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: ponos-secret
                key: SLACK_TOKEN

      volumes:
        - name: github-pem
          secret:
            secretName: github-pem-secret









