---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ponos-server-ingress
  namespace: ponos-server
  labels:
    name: ponos-server
spec:
  ingressClassName: nginx
  rules:
    - host: ponos-server.blockops.network
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: ponos-server
                port:
                  number: 8700
