---
apiVersion: v1
kind: Service
metadata:
  name: ponos-server
  namespace: ponos-server
  labels:
    app: ponos-server
spec:
  selector:
    app: ponos-server
  ports:
    - name: ponos-server-metrics
      protocol: TCP
      port: 8000
      targetPort: 8700
