---
apiVersion: v1
kind: Service
metadata:
  name: ponos
  namespace: ponos
  labels:
    app: ponos
spec:
  selector:
    app: ponos
  ports:
    - name: ponos-metrics
      protocol: TCP
      port: 8000
      targetPort: 8700