name: k8s-deploy
on:
  push:
    branches:
      - main

jobs:
  cluster_deploy:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set_env
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          if [ "$BRANCH" = "main" ]; then
            echo "ENVIRONMENT=ponos" >> $GITHUB_ENV
          fi

      - name: Set image tag
        id: set_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Remove the leading 'v' from the tag name
            TAG=${GITHUB_REF#refs/tags/v}
            echo "TAG=${TAG}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: blockopsnetwork/ponos:${{ env.TAG }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [ "${{ env.BRANCH }}" = "main" ]; then
            EXPIRY=1000
          elif [ "${{ env.BRANCH }}" = "dev" ]; then
            EXPIRY=600
          else
            EXPIRY=1000
          fi
          doctl kubernetes cluster kubeconfig save --expiry-seconds $EXPIRY blockops-testnet

      - uses: azure/setup-kubectl@v4
        id: install

      - name: Deploy to Cluster
        if: ${{ github.event_name != 'pull_request' }}
        env:
          DOCKERHUB_REPO: blockopsartifacts
          APP_NAME: blockproxy
          BRANCH: ${{ env.BRANCH }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          IMG_NAME: blockopsnetwork/ponos:${{ env.TAG }}
        run: |
          /bin/bash deploy.sh